name: nightly-release

on:
  push:
    branches:
      - master
      - '[0-9]+.*'
      - 'ci-*'
    tags:
      - '*'
permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  nightly-release:
    runs-on: ubuntu-22.04
    needs: ci
    if: github.repository == 'PAIA-Playful-AI-Arena/paia_tensorboard'
    steps:
      - name: Download pip package
        uses: actions/download-artifact@v4
        with:
          pattern: tb-nightly_py*
          # Download all matching artifacts in the same directory (specified by path)
          merge-multiple: true
          path: wheels
      - name: Install Twine
        run: pip install twine
      - name: Publish the package
        run: |
          twine check tb_nightly*.whl
          twine upload tb_nightly*.whl
        working-directory: wheels
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.NIGHTLY_PYPI_PASSWORD }}


  # pypi-publish:
  #   name: Upload release to PyPI
  #   runs-on: ubuntu-22.04
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/paia_tensorboard
  #   permissions:
  #     id-token: write
  #   steps:
  #   # retrieve your distributions here

  #   - name: Publish package distributions to PyPI
  #     uses: pypa/gh-action-pypi-publish@release/v1
  #     with:
  #       verbose: true
  #       print-hash: true
  #       directory: wheels