name: nightly-release

on:
  push:
    branches:
      - master
      - '[0-9]+.*'
      - 'ci-*'
    tags:
      - '*'
permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  nightly-release:
    runs-on: ubuntu-22.04
    needs: ci
    if: github.repository == 'PAIA-Playful-AI-Arena/paia_tensorboard'
    steps:
      - name: Download pip package
        uses: actions/download-artifact@v4
        with:
          pattern: tb-nightly_py*
          # Download all matching artifacts in the same directory (specified by path)
          merge-multiple: true
          path: wheels
      - name: Install Twine
        run: pip install twine
      - name: Check the package
        run: |
          twine check tb_nightly*.whl
        working-directory: wheels

      - name: Publish the package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
